cpejr/webvet

package-lock.json
package.json

Vou tentar dar merge no branch criado pelo Arthur Braga com objetivo de corrigir os erros de npm install que tivemos no primeiro sprint

Correção do npm install

---

views/allsamples.hbs

O nome do segundo campo tem a adição de um "2"
Exemplo:
nome do primeiro campo = "aflaCalibrator[P1]"
nome do segundo = "aflaCalibrator2[P1]"

Novos campos de input para /allsamples

---

views/allsamples.hbs

Melhorei o bootstrap da tabela, deve estar mais responsiva que antes.

Modificações no layout da tabela /allsamples

---

views/allsamples.hbs

Resolvi alguns problemas com o tamanho dos inputs, agora o display são de duas colunas de três tabelas, em vez de uma coluna com seis tabelas.

Formatação V2

---

views/allsamples.hbs

Corrigindo erro do /allsamples que não deveria ter 2 inputs (My bad)

Tirando inputs duplos

---

views/allsamples.hbs

Revertendo minhas mudanças que deixaram /allsamples com duas linhas de 3 tabelas.

/allsamples agora tem 6 tabelas alinhadas

---

views/allsamples.hbs

Agora os campos de input são muito mais legíveis

Correção de modelo de /allsamples

---

views/allworkmaps.hbs

Minha tentativa de melhorar o layout dessa página

Primeira mudança p/ organizar /allworkmaps

---

views/allsamples.hbs
views/allworkmaps.hbs

Concatenação de código e criação de novas divs

Segundo passo para melhorar workmaps

---

models/sample.js
routes/allworkmaps.js
views/allworkmaps.hbs

Foi criado no schema uma nova função para atualizar valores no banco de dados.
Fizemos o novo campo absorvance2 funcionar

Back do allworkmaps e allsamples

---

views/calibrationcurves.hbs

Neste commit adiciono o botão que irá retornar para a página de curvas de calibração

Novo botão

---

routes/calibrationcurves.js
routes/sampleresult.js
views/calibrationcurves.hbs

Estamos adicionando tabelas na página de calibração de curvas

Calibrationcurves2

---

routes/calibrationcurves.js
views/calibrationcurves.hbs

Acabei empolgando e por acidente terminei a table

---

views/calibrationcurves.hbs

Ajustes nos valores 

---

routes/sampleresult.js
views/sampleresult.hbs

Este form será responsável por enviar os dados da tabela para a rota post de /sampleresult. Onde iremos alterar o estado "active" dos samples presentes.

Criando form em sampleresult

---

routes/allworkmaps.js

Como ficou decidido, estou removendo o pedaço que seta o atributo "active" dos samples como false no botão finalizar do /allwormaps

Removendo "Active" de allworkmaps

---

models/sample.js
routes/report.js
views/report/admreport.hbs
views/report/editAdmin.hbs
views/report/show.hbs

Além disso os relatórios agora puxam o samplenumber e ano na página de relatórios.

O Botão "Gerar Laudo" de /sampleresult seta "report" como "true".

---

models/sample.js
views/report/editAdmin.hbs

Por enquanto estou usando Date.getFullYear(). Não sei se isso significa estar usando a data do computador ou não...

Guardando ano de criação no sample

---

routes/report.js
routes/sampleresult.js

Nada que eu tentei fazer para puxar os valores de lod e loq do Kit em cada toxina de cada amostra funcionou. Frustrante.
Arrumei uma função que estava sendo chamada com o nome errado (provavelmente)

Tentativa de preparar loq e lod

---

routes/allsamples.js
routes/calibrationcurves.js
views/calibrationcurves.hbs

Resolvendo bugs no calibration curves. Impediam que os dados de calibração e absorvância fossem puxados da base de dados mesmo que eles estivessem sendo setados corretamente em /allworkmaps.

Calibration curves

---

models/Workmap.js
routes/allworkmaps.js
routes/sampleresult.js

De bônus otimizamos o programa

Correção bugs

---

models/kit.js
models/sample.js
routes/report.js
views/report/editAdmin.hbs

Merge que aparentemente consegue puxar os kits dos ids

---

routes/report.js
views/report/editAdmin.hbs

Não creio que esse negócio deu certo e por favor não quebre

Loq e Lod FUNCIONAIS ALELUIA AMEM

---

routes/sampleresult.js

é isso ai, corrigiu o bug chato

Sampleresults redireciona para laudos

---

routes/report.js
views/report/admreport.hbs

Corrigindo numeros da pagina de laudos

---

models/Workmap.js
models/requisition.js
models/sample.js
routes/requisition.js
routes/sample.js
views/requisition/show.hbs

agora quando apaga a requisition, apaga as samples.
Quando apaga as samples verifica se ela está em algum workmap, se estiver o id dela será removido do workmap.

Requisition está sendo apagada de forma correta

---

routes/requisition.js
views/admin/homeAdmin.hbs
views/requisition/edit.hbs
views/requisition/index.hbs
views/requisition/show.hbs

Tentando fazer o edit de requisition funcionar

---

views/report/editAdmin.hbs

Melhorias no laudo

---

views/report/editAdmin.hbs

Parecer técnico está completamente funcional

---

routes/report.js

Laudo muito melhor

---

views/requisition/edit.hbs

Com objetivo de evitar problemas na base de dados

Forçando input do tipo number

---

routes/users.js
views/admin/users/show.hbs

Arrumando user

---

routes/report.js
routes/requisition.js

Fiz a mudança para que os vetores resultado sejam invertidos antes de serem mandados para o front

Laudos e Requisições do admin invertidos.

---

routes/user.js
views/user.hbs

A página do usuário agora mostra os laudos

---

models/sample.js
routes/report.js
routes/user.js
views/report/admreport.hbs
views/report/editAdmin.hbs
views/report/show.hbs
views/user.hbs

Os laudos agora podem ser manualmente finalizados pelo administrador e somente aqueles que estão finalizados aparecerão para o produtor.

Lógica de finalização de laudos completa e funcional.

---

models/sample.js
routes/report.js

Sem dar overwrite no que está escrito em cada toxina! é um milagre!

Inputs do laudo salvam corretamente

---

routes/user.js
views/user.hbs

Os botões das requisitions agora são funcionais assim como os botões dos laudos na página inicial do usuário.

O usuário agora pode ir para a página /show de requisitions

---

models/kit.js
routes/stock.js
views/stock/edit.hbs

Ia ser muito trampo, muito BO e ela nunca vai fazer isso

Não pode mais editar o número de workmaps

---

package-lock.json
routes/record.js

Consertei um problema no /record dos produtores

Consertei um problema no /record dos produtores
